# Generated by Django 5.0.4 on 2024-05-10 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacao', '0002_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cargo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='authenticacao.cargo'),
        ),
    ]
